testDjango/part/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'part'

urlpatterns = [

    path('', views.IndexView.as_view() , name='index'),
    path('<int:pk>/', views.DetailView.as_view() , name='part_detail'),
    path('add/', views.PartCreate.as_view(), name="part_add"),
    path('register/', views.UserFormView.as_view(), name="register"),
    path('update/<int:pk>/', views.PartUpdate.as_view(), name="part_update"),
    path('delete/<int:pk>/', views.PartDelete.as_view(), name="part_delete")

]

testDjango/testDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('part.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testDjango/part/models.py
from django.db import models
from django.urls import reverse

class Part(models.Model):
    first_prop = models.CharField(max_length=255)
    second_prop = models.CharField(max_length=250)
    third_prop = models.BooleanField(default=False)
    img_link = models.FileField()

    def get_absolute_url(self):
        return reverse('part:part_detail', kwargs={'pk' : self.pk})

    def __str__(self):
        return self.first_prop + ' - ' + self.second_prop

class Next(models.Model):
    part = models.ForeignKey(Part, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    next_title = models.CharField(max_length=252)

    def __str__(self):
        return self.file_type

testDjango/part/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

testDjango/part/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Part
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm

class IndexView(generic.ListView):
    template_name = 'part/index.html'
    context_object_name = 'part_list'

    def get_queryset(self):
        return Part.objects.all()

class DetailView(generic.DetailView):
    model = Part
    template_name = 'part/detail.html'

class PartCreate(CreateView):
    model = Part
    fields = [
        'first_prop',
        'second_prop',
        'third_prop',
        'img_link'
    ]

class PartUpdate(UpdateView):
    model = Part
    fields = [
        'first_prop',
        'second_prop',
        'third_prop'
    ]

class PartDelete(DeleteView):
    model = Part
    success_url = reverse_lazy('part:index')

class UserFormView(View):
    form_class = UserForm
    template_name = 'part/registration_form.html'

    # display form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})

    # register user
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            # cleaned data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('part:index')

        return render(request, self.template_name, {'form': form})

testDjango/part/templates/part/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Website</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'music/style.css' %}">
</head>
<body>

{% block body %}{% endblock %}
<a href="{% url 'part:part_add' %}">Add Part</a>
</body>
</html>

testDjango/part/templates/part/detail.html
{% extends 'part/base.html' %}

{% block body %}

    <h1>{{ part }}</h1>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

{% endblock %}

testDjango/part/templates/part/form-template.html
{% for field in form %}
    {{ field.errors }}
    {{ field.label_tag }}
    {{ field }}
    <br>
{% endfor %}

testDjango/part/templates/part/index.html
{% extends 'part/base.html' %}


{% block body %}
    <ul>

        {% if object_list %}
            <h3>Parts</h3>
            {% for part in part_list %}
                <div class="img">
                    <img src="{{ part.img_link.url }}" alt="some-img">
                </div>
                <li>
                    <a href="{% url 'part:part_detail' part.id %}">{{ part.first_prop }}</a>
                    <form action="{% url 'part:part_delete' part.id %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="part_id" value="{{ part.id }}">
                        <br>
                        <button type="submit">
                            Delete
                        </button>
                    </form>
                </li>
            {% endfor %}

        {% else %}
            <li><h2>You dont have any parts</h2></li>
        {% endif %}

    </ul>
{% endblock %}

testDjango/part/templates/part/part_form.html
{% extends 'part/base.html' %}

{% block body %}
    <form action="{% url 'part:part_add' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'part/form-template.html' %}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

testDjango/part/templates/part/registration_form.html
{% extends 'part/base.html' %}

{% block body %}
    <h1>Create an account</h1>
    <form action="" method="post">
        {% csrf_token %}
        {% include 'part/form-template.html' %}
        <button type="submit">Submit</button>
    </form>
{% endblock %}